linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - gosimple
    - gocritic

linters-settings:
  gosec:
    excludes:
      - G304 # File path provided as taint input - we validate save_path
  errcheck:
    check-blank: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
