version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - gocritic
  settings:
    gosec:
      excludes:
        - G304 # File path provided as taint input - we validate save_path
    errcheck:
      check-blank: false
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
